openapi: 3.0.2
servers: []
info:
  version: "0.1"
  title: GA4GH Beacon Veriant Default Schema
  description: >-
    Schema for variants to be used as default by the Beacon.
  contact:
    email: beacon@ga4gh.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: |
    'Beacon Project'
  url: 'http://beacon-project.io/'
paths: {}
components:
  schemas:
    Chromosome:
      description: |
        Reference name (chromosome). Accepting values 1-22, X, Y, MT.
      type: string
      enum:
        - '1'
        - '2'
        - '3'
        - '4'
        - '5'
        - '6'
        - '7'
        - '8'
        - '9'
        - '10'
        - '11'
        - '12'
        - '13'
        - '14'
        - '15'
        - '16'
        - '17'
        - '18'
        - '19'
        - '20'
        - '21'
        - '22'
        - 'X'
        - 'Y'
        - 'MT'
    VariantDetails:
      description: |
        Description of the variant.
      type: object
      properties:
        chromosome:
          $ref: '#/components/schemas/Chromosome'
        referenceBases:
          description: |
            Reference bases for this variant (starting from `start`).
          type: string
          pattern: '^([ACGTN]+)$'
        alternateBases:
          description: |
            The bases that appear instead of the reference bases.
          type: string
          pattern: '^([ACGTN]+)$'
        variantType:
          description: |
            Ontology value from Sequence Ontology describing the type of 
            variant, e.g. SNV (SO:0001483), structural variant(SO:0001537).
          type: string
          example: SO:0001483
        start:
          description: |
            Start position of variant.
          type: integer
          format: int64
          minimum: 0
        end:
          description: |
            End position of variant
          type: integer
          format: int64
          minimum: 0
        assemblyId:
          description: |
            Genomic assembly accession as Genome Reference consortium Human 
            name, e.g. GRCh38.
          type: string
          example: GRCh38
        info:
          description: |
            Additional unspecified metadata about the dataset response or its 
            content.
          type: object
          example:
            additionalInfoKey1: 
              - additionalInfoValue1
              - additionalInfoValue2
            additionalInfoKey2: additionalInfoValue3
